Getting started:
- "One-click Services"

Web hosting:
- "Heroku Service"
- "GitHub Pages"
- "WordPress Service"
- "Webflow Service"
- "Weebly Service"
- "Surge Service"
- "Format Service"
- "Geniuslink Service"
- "Gigalixir Service"
- "Jimdo Service"
- "Platform.sh Service"
- "Tumblr Service"
- "Blogger Service"
- "LaunchRock Service"

Productivity:
- "Google Workspace (formerly G Suite) Service"
- "Office 365 Service"
- "KickOffLabs Service"
- "Tender Service"

Email:
- "Fastmail Service"
- "Divio Aldryn Service"
- "Atmail Service"
- "Mailgun Service"
- "Pobox Service"
- "Postmark Service"
- "Rackspace Email Service"
- "DMARC Reports by Postmark Service"

E-commerce:
- "Shopify Service"
- "Squarespace Service"
- "Blackbell Service"
- "SupaDupa Service"

Infrastructure:
- "AWS Elastic Beanstalk Service"
- "AWS Lightsail Service"
- "AWS S3 Service"
- "Cloudflare Service"
- "Fanout Service"
- "Fastly Service"
- "Netlify Service"
- "Windows Azure Service"
- "URL Forwarding Service"
